#ifndef C_COLOR_PRESET_H
#define C_COLOR_PRESET_H

#include "../lib.h"
#include "./CColor.h"

class CColorPreset
{
private:
    explicit CColorPreset();
    ~CColorPreset();

public:
    static const CColor almond;
    static const CColor antique_brass;
    static const CColor apricot;
    static const CColor aquamarine;
    static const CColor asparagus;
    static const CColor atomic_tangerine;
    static const CColor banana_mania;
    static const CColor beaver;
    static const CColor bittersweet;
    static const CColor black;
    static const CColor blizzard_blue;
    static const CColor blue;
    static const CColor blue_bell;
    static const CColor blue_gray;
    static const CColor blue_green;
    static const CColor blue_violet;
    static const CColor blush;
    static const CColor brick_red;
    static const CColor brown;
    static const CColor burnt_orange;
    static const CColor burnt_sienna;
    static const CColor cadet_blue;
    static const CColor canary;
    static const CColor caribbean_green;
    static const CColor carnation_pink;
    static const CColor cerise;
    static const CColor cerulean;
    static const CColor chestnut;
    static const CColor copper;
    static const CColor cornflower;
    static const CColor cotton_candy;
    static const CColor dandelion;
    static const CColor denim;
    static const CColor desert_sand;
    static const CColor eggplant;
    static const CColor electric_lime;
    static const CColor fern;
    static const CColor forest_green;
    static const CColor fuchsia;
    static const CColor fuzzy_wuzzy;
    static const CColor gold;
    static const CColor goldenrod;
    static const CColor granny_smith_apple;
    static const CColor gray;
    static const CColor green;
    static const CColor green_blue;
    static const CColor green_yellow;
    static const CColor hot_magenta;
    static const CColor inchworm;
    static const CColor indigo;
    static const CColor jazzberry_jam;
    static const CColor jungle_green;
    static const CColor laser_lemon;
    static const CColor lavender;
    static const CColor lemon_yellow;
    static const CColor macaroni_and_cheese;
    static const CColor magenta;
    static const CColor magic_mint;
    static const CColor mahogany;
    static const CColor maize;
    static const CColor manatee;
    static const CColor mango_tango;
    static const CColor maroon;
    static const CColor mauvelous;
    static const CColor melon;
    static const CColor midnight_blue;
    static const CColor mountain_meadow;
    static const CColor mulberry;
    static const CColor navy_blue;
    static const CColor neon_carrot;
    static const CColor olive_green;
    static const CColor orange;
    static const CColor orange_red;
    static const CColor orange_yellow;
    static const CColor orchid;
    static const CColor outer_space;
    static const CColor outrageous_orange;
    static const CColor pacific_blue;
    static const CColor peach;
    static const CColor periwinkle;
    static const CColor piggy_pink;
    static const CColor pine_green;
    static const CColor pink_flamingo;
    static const CColor pink_sherbet;
    static const CColor plum;
    static const CColor purple_heart;
    static const CColor purple_mountains_majesty;
    static const CColor purple_pizzazz;
    static const CColor radical_red;
    static const CColor raw_sienna;
    static const CColor raw_umber;
    static const CColor razzle_dazzle_rose;
    static const CColor razzmatazz;
    static const CColor red;
    static const CColor red_orange;
    static const CColor red_violet;
    static const CColor robins_egg_blue;
    static const CColor royal_purple;
    static const CColor salmon;
    static const CColor scarlet;
    static const CColor screamin_green;
    static const CColor sea_green;
    static const CColor sepia;
    static const CColor shadow;
    static const CColor shamrock;
    static const CColor shocking_pink;
    static const CColor silver;
    static const CColor sky_blue;
    static const CColor spring_green;
    static const CColor sunglow;
    static const CColor sunset_orange;
    static const CColor tan;
    static const CColor teal_blue;
    static const CColor thistle;
    static const CColor tickle_me_pink;
    static const CColor timberwolf;
    static const CColor tropical_rain_forest;
    static const CColor tumbleweed;
    static const CColor turquoise_blue;
    static const CColor unmellow_yellow;
    static const CColor violet;
    static const CColor violet_blue;
    static const CColor violet_red;
    static const CColor vivid_tangerine;
    static const CColor vivid_violet;
    static const CColor white;
    static const CColor wild_blue_yonder;
    static const CColor wild_strawberry;
    static const CColor wild_watermelon;
    static const CColor wisteria;
    static const CColor yellow;
    static const CColor yellow_green;
    static const CColor yellow_orange;

    static CColor ui_background;
    static CColor ui_title_fg;
    static CColor ui_title_bg;
    static CColor ui_title_focus;
    static CColor ui_frame_fg;
    static CColor ui_frame_bg;
    static CColor ui_component_fg;
    static CColor ui_component_bg;
    static CColor ui_text;
    static CColor ui_edit;
};

#endif // C_COLOR_PRESET_H
